services:
  server:
    build:
      context: ./server
    image: docker/server
    container_name: server
    ports:
      - "8000:8000"

  client:
    build:
      context: ./client
    image: dockerfile/client
    container_name: client
    depends_on:
      - server