
services:
  server:
    # ###
    # 다음 주석을 지우고 compose 를 완성하자
    # ###
    build: ./server
    volumes:
      - ./server:/app


  client:
    # compose 를 완성하자
    build: ./client
    volumes:
      - ./client:/app
    depends_on:
      - server
